#pragma once
// Copyright (c) 2020 Cvelth.
//
// SPDX-License-Identifier: Apache-2.0
//

#if defined(_MSVC_LANG)
#  define VKFW_HPP_CPLUSPLUS _MSVC_LANG
#else
#  define VKFW_HPP_CPLUSPLUS __cplusplus
#endif

#if 201703L < VKFW_HPP_CPLUSPLUS
#  define VKFW_HPP_CPP_VERSION 20
#elif 201402L < VKFW_HPP_CPLUSPLUS
#  define VKFW_HPP_CPP_VERSION 17
#elif 201103L < VKFW_HPP_CPLUSPLUS
#  define VKFW_HPP_CPP_VERSION 14
#elif 199711L < VKFW_HPP_CPLUSPLUS
#  define VKFW_HPP_CPP_VERSION 11
#else
#  error "vkfw.hpp needs at least c++ standard version 11"
#endif

// Standard library includes go here!
#include <string>

#if 17 <= VULKAN_HPP_CPP_VERSION
#  include <string_view>
#endif

#if !defined(VKFW_INCLUDE_GL)
#  define GLFW_INCLUDE_NONE
#endif

#include <GLFW/glfw3.h>
#if !defined(VKFW_HPP_NO_INCLUDE_VULKAN_HPP)
#  include <vulkan/vulkan.hpp>
#endif

#if defined(VKFW_HPP_DISABLE_ENHANCED_MODE)
#  if !defined(VKFW_HPP_NO_SMART_HANDLE)
#    define VKFW_HPP_NO_SMART_HANDLE
#  endif
#else
#  include <memory>
#  include <vector>
#endif

#if !defined(VKFW_HPP_ASSERT)
#  include <cassert>
#  define VKFW_HPP_ASSERT assert
#endif

#if !defined(VKFW_HPP_ASSERT_ON_RESULT)
# define VKFW_HPP_ASSERT_ON_RESULT VKFW_HPP_ASSERT
#endif

#define VKFW_VERSION_MAJOR 0
#define VKFW_VERSION_MINOR 3
#define VKFW_VERSION_PATCH 0
static_assert(GLFW_VERSION_MAJOR == 3
			  && GLFW_VERSION_MINOR == 3
			  && GLFW_VERSION_REVISION == 2
			  , "\"glfw3.h\" version is not compatible with the \"vkfw.hpp\" version!");

#if !defined(VKFW_HPP_INLINE)
#  if defined(__clang__)
#    if __has_attribute(always_inline)
#      define VKFW_HPP_INLINE __attribute__((always_inline)) __inline__
#    else
#      define VKFW_HPP_INLINE inline
#    endif
#  elif defined(__GNUC__)
#    define VKFW_HPP_INLINE __attribute__((always_inline)) __inline__
#  elif defined(_MSC_VER)
#    define VKFW_HPP_INLINE inline
#  else
#    define VKFW_HPP_INLINE inline
#  endif
#endif

#if defined(VKFW_HPP_TYPESAFE_CONVERSION)
#  define VKFW_HPP_TYPESAFE_EXPLICIT
#else
#  define VKFW_HPP_TYPESAFE_EXPLICIT explicit
#endif

#if defined(__cpp_constexpr)
#  define VKFW_HPP_CONSTEXPR constexpr
#  if __cpp_constexpr >= 201304
#    define VKFW_HPP_CONSTEXPR_14  constexpr
#  else
#    define VKFW_HPP_CONSTEXPR_14
#  endif
#  define VKFW_HPP_CONST_OR_CONSTEXPR  constexpr
#else
#  define VKFW_HPP_CONSTEXPR
#  define VKFW_HPP_CONSTEXPR_14
#  define VKFW_HPP_CONST_OR_CONSTEXPR  const
#endif

#if !defined(VKFW_HPP_NOEXCEPT)
#  if defined(_MSC_VER) && (_MSC_VER <= 1800)
#    define VKFW_HPP_NOEXCEPT
#  else
#    define VKFW_HPP_NOEXCEPT noexcept
#    define VKFW_HPP_HAS_NOEXCEPT 1
#  endif
#endif

#if 14 <= VKFW_HPP_CPP_VERSION
#  define VKFW_HPP_DEPRECATED( msg ) [[deprecated( msg )]]
#else
#  define VKFW_HPP_DEPRECATED( msg )
#endif

#if ( 17 <= VKFW_HPP_CPP_VERSION ) && !defined( VKFW_HPP_NO_NODISCARD_WARNINGS )
#  define VKFW_HPP_NODISCARD [[nodiscard]]
#  if defined(VKFW_HPP_NO_EXCEPTIONS)
#    define VKFW_HPP_NODISCARD_WHEN_NO_EXCEPTIONS [[nodiscard]]
#  else
#    define VKFW_HPP_NODISCARD_WHEN_NO_EXCEPTIONS
#  endif
#else
#  define VKFW_HPP_NODISCARD
#  define VKFW_HPP_NODISCARD_WHEN_NO_EXCEPTIONS
#endif

#if !defined(VKFW_HPP_NAMESPACE)
#define VKFW_HPP_NAMESPACE vkfw
#endif

#define VKFW_HPP_STRINGIFY2(text) #text
#define VKFW_HPP_STRINGIFY(text) VKFW_HPP_STRINGIFY2(text)
#define VKFW_HPP_NAMESPACE_STRING VKFW_HPP_STRINGIFY(VKFW_HPP_NAMESPACE)

#if !(defined(VKFW_HPP_CHAR_T) && defined(VKFW_HPP_CHAR_LITERAL))
#  if defined(VKFW_HPP_USE_CHAR8_T) && defined(__cpp_char8_t) && defined(__cpp_lib_char8_t)
#    define VKFW_HPP_CHAR_T char8_t
#    define VKFW_HPP_CHAR_LITERAL u8""
#  elif defined(VKFW_HPP_USE_CHAR16_T)
#    define VKFW_HPP_CHAR_T char16_t
#    define VKFW_HPP_CHAR_LITERAL u""
#  elif defined(VKFW_HPP_USE_CHAR32_T)
#    define VKFW_HPP_CHAR_T char32_t
#    define VKFW_HPP_CHAR_LITERAL U""
#  elif defined(VKFW_HPP_USE_WCHAR_T)
#    define VKFW_HPP_CHAR_T wchar_t
#    define VKFW_HPP_CHAR_LITERAL L""
#  else
#    define VKFW_HPP_CHAR_T char
#    define VKFW_HPP_CHAR_LITERAL
#  endif
#endif

#define VKFW_HPP_STRING_T std::basic_string<VKFW_HPP_CHAR_T>
#if 17 <= VKFW_HPP_CPP_VERSION
#  define VKFW_HPP_STRING_VIEW_T std::basic_string_view<VKFW_HPP_CHAR_T>
#endif

#if defined(VKFW_HPP_NO_LEADING_e_IN_ENUMS)
#  define VKFW_HPP_ENUMERATOR(name) name
#  define VKFW_HPP_ENUMERATOR2(name_1, name_2) name_2
#else
#  define VKFW_HPP_ENUMERATOR(name) e ## name
#  define VKFW_HPP_ENUMERATOR2(name_1, name_2) e ## name_1
#endif

namespace VKFW_HPP_NAMESPACE {
	enum class Boolean {
		VKFW_HPP_ENUMERATOR(True) = GLFW_TRUE,
		VKFW_HPP_ENUMERATOR(False) = GLFW_FALSE
	};
	enum class KeyAction {
		VKFW_HPP_ENUMERATOR(Release) = GLFW_RELEASE,
		VKFW_HPP_ENUMERATOR(Press) = GLFW_PRESS,
		VKFW_HPP_ENUMERATOR(Repeat) = GLFW_REPEAT
	};
	enum class MouseButtonAction {
		VKFW_HPP_ENUMERATOR(Release) = GLFW_RELEASE,
		VKFW_HPP_ENUMERATOR(Press) = GLFW_PRESS
	};
	enum class JoystickHatState {
		VKFW_HPP_ENUMERATOR(Centered) = GLFW_HAT_CENTERED,
		VKFW_HPP_ENUMERATOR(Up) = GLFW_HAT_UP,
		VKFW_HPP_ENUMERATOR(Right) = GLFW_HAT_RIGHT,
		VKFW_HPP_ENUMERATOR(Down) = GLFW_HAT_DOWN,
		VKFW_HPP_ENUMERATOR(Left) = GLFW_HAT_LEFT,
		VKFW_HPP_ENUMERATOR(Right_Up) = GLFW_HAT_RIGHT_UP,
		VKFW_HPP_ENUMERATOR(Right_Down) = GLFW_HAT_RIGHT_DOWN,
		VKFW_HPP_ENUMERATOR(Left_Up) = GLFW_HAT_LEFT_UP,
		VKFW_HPP_ENUMERATOR(Left_Down) = GLFW_HAT_LEFT_DOWN
	};

	enum class Key {
		/* The unknown Key */
		VKFW_HPP_ENUMERATOR(Unknown) = GLFW_KEY_UNKNOWN,

		/* Printable Keys */
		VKFW_HPP_ENUMERATOR(Space) = GLFW_KEY_SPACE,
		VKFW_HPP_ENUMERATOR(Apostrophe) = GLFW_KEY_APOSTROPHE,		/* ' */
		VKFW_HPP_ENUMERATOR(Comma) = GLFW_KEY_COMMA,				/* , */
		VKFW_HPP_ENUMERATOR(Minus) = GLFW_KEY_MINUS,				/* - */
		VKFW_HPP_ENUMERATOR(Period) = GLFW_KEY_PERIOD,				/* . */
		VKFW_HPP_ENUMERATOR(Slash) = GLFW_KEY_SLASH,				/* / */
		VKFW_HPP_ENUMERATOR2(0, _0) = GLFW_KEY_0,
		VKFW_HPP_ENUMERATOR2(1, _1) = GLFW_KEY_1,
		VKFW_HPP_ENUMERATOR2(2, _2) = GLFW_KEY_2,
		VKFW_HPP_ENUMERATOR2(3, _3) = GLFW_KEY_3,
		VKFW_HPP_ENUMERATOR2(4, _4) = GLFW_KEY_4,
		VKFW_HPP_ENUMERATOR2(5, _5) = GLFW_KEY_5,
		VKFW_HPP_ENUMERATOR2(6, _6) = GLFW_KEY_6,
		VKFW_HPP_ENUMERATOR2(7, _7) = GLFW_KEY_7,
		VKFW_HPP_ENUMERATOR2(8, _8) = GLFW_KEY_8,
		VKFW_HPP_ENUMERATOR2(9, _9) = GLFW_KEY_9,
		VKFW_HPP_ENUMERATOR(Semicolon) = GLFW_KEY_SEMICOLON,		/* ; */
		VKFW_HPP_ENUMERATOR(Equal) = GLFW_KEY_EQUAL,				/* = */
		VKFW_HPP_ENUMERATOR(A) = GLFW_KEY_A,
		VKFW_HPP_ENUMERATOR(B) = GLFW_KEY_B,
		VKFW_HPP_ENUMERATOR(C) = GLFW_KEY_C,
		VKFW_HPP_ENUMERATOR(D) = GLFW_KEY_D,
		VKFW_HPP_ENUMERATOR(E) = GLFW_KEY_E,
		VKFW_HPP_ENUMERATOR(F) = GLFW_KEY_F,
		VKFW_HPP_ENUMERATOR(G) = GLFW_KEY_G,
		VKFW_HPP_ENUMERATOR(H) = GLFW_KEY_H,
		VKFW_HPP_ENUMERATOR(I) = GLFW_KEY_I,
		VKFW_HPP_ENUMERATOR(J) = GLFW_KEY_J,
		VKFW_HPP_ENUMERATOR(K) = GLFW_KEY_K,
		VKFW_HPP_ENUMERATOR(L) = GLFW_KEY_L,
		VKFW_HPP_ENUMERATOR(M) = GLFW_KEY_M,
		VKFW_HPP_ENUMERATOR(N) = GLFW_KEY_N,
		VKFW_HPP_ENUMERATOR(O) = GLFW_KEY_O,
		VKFW_HPP_ENUMERATOR(P) = GLFW_KEY_P,
		VKFW_HPP_ENUMERATOR(Q) = GLFW_KEY_Q,
		VKFW_HPP_ENUMERATOR(R) = GLFW_KEY_R,
		VKFW_HPP_ENUMERATOR(S) = GLFW_KEY_S,
		VKFW_HPP_ENUMERATOR(T) = GLFW_KEY_T,
		VKFW_HPP_ENUMERATOR(U) = GLFW_KEY_U,
		VKFW_HPP_ENUMERATOR(V) = GLFW_KEY_V,
		VKFW_HPP_ENUMERATOR(W) = GLFW_KEY_W,
		VKFW_HPP_ENUMERATOR(X) = GLFW_KEY_X,
		VKFW_HPP_ENUMERATOR(Y) = GLFW_KEY_Y,
		VKFW_HPP_ENUMERATOR(Z) = GLFW_KEY_Z,
		VKFW_HPP_ENUMERATOR(LeftBracket) = GLFW_KEY_LEFT_BRACKET,	/* [ */
		VKFW_HPP_ENUMERATOR(Backslash) = GLFW_KEY_BACKSLASH,		/* \ */
		VKFW_HPP_ENUMERATOR(RightBracket) = GLFW_KEY_RIGHT_BRACKET,	/* ] */
		VKFW_HPP_ENUMERATOR(GraveAccent) = GLFW_KEY_GRAVE_ACCENT,	/* ` */
		VKFW_HPP_ENUMERATOR(World1) = GLFW_KEY_WORLD_1,				/* non-US #1 */
		VKFW_HPP_ENUMERATOR(World2) = GLFW_KEY_WORLD_2,				/* non-US #2 */

		/* Function Keys */
		VKFW_HPP_ENUMERATOR(Escape) = GLFW_KEY_ESCAPE,
		VKFW_HPP_ENUMERATOR(Enter) = GLFW_KEY_ENTER,
		VKFW_HPP_ENUMERATOR(Tab) = GLFW_KEY_TAB,
		VKFW_HPP_ENUMERATOR(Backspace) = GLFW_KEY_BACKSPACE,
		VKFW_HPP_ENUMERATOR(Insert) = GLFW_KEY_INSERT,
		VKFW_HPP_ENUMERATOR(Delete) = GLFW_KEY_DELETE,
		VKFW_HPP_ENUMERATOR(Right) = GLFW_KEY_RIGHT,
		VKFW_HPP_ENUMERATOR(Left) = GLFW_KEY_LEFT,
		VKFW_HPP_ENUMERATOR(Down) = GLFW_KEY_DOWN,
		VKFW_HPP_ENUMERATOR(Up) = GLFW_KEY_UP,
		VKFW_HPP_ENUMERATOR(PageUp) = GLFW_KEY_PAGE_UP,
		VKFW_HPP_ENUMERATOR(PageDown) = GLFW_KEY_PAGE_DOWN,
		VKFW_HPP_ENUMERATOR(Home) = GLFW_KEY_HOME,
		VKFW_HPP_ENUMERATOR(End) = GLFW_KEY_END,
		VKFW_HPP_ENUMERATOR(CapsLock) = GLFW_KEY_CAPS_LOCK,
		VKFW_HPP_ENUMERATOR(ScrollLock) = GLFW_KEY_SCROLL_LOCK,
		VKFW_HPP_ENUMERATOR(NumLock) = GLFW_KEY_NUM_LOCK,
		VKFW_HPP_ENUMERATOR(PrintScreen) = GLFW_KEY_PRINT_SCREEN,
		VKFW_HPP_ENUMERATOR(Pause) = GLFW_KEY_PAUSE,
		VKFW_HPP_ENUMERATOR(F1) = GLFW_KEY_F1,
		VKFW_HPP_ENUMERATOR(F2) = GLFW_KEY_F2,
		VKFW_HPP_ENUMERATOR(F3) = GLFW_KEY_F3,
		VKFW_HPP_ENUMERATOR(F4) = GLFW_KEY_F4,
		VKFW_HPP_ENUMERATOR(F5) = GLFW_KEY_F5,
		VKFW_HPP_ENUMERATOR(F6) = GLFW_KEY_F6,
		VKFW_HPP_ENUMERATOR(F7) = GLFW_KEY_F7,
		VKFW_HPP_ENUMERATOR(F8) = GLFW_KEY_F8,
		VKFW_HPP_ENUMERATOR(F9) = GLFW_KEY_F9,
		VKFW_HPP_ENUMERATOR(F10) = GLFW_KEY_F10,
		VKFW_HPP_ENUMERATOR(F11) = GLFW_KEY_F11,
		VKFW_HPP_ENUMERATOR(F12) = GLFW_KEY_F12,
		VKFW_HPP_ENUMERATOR(F13) = GLFW_KEY_F13,
		VKFW_HPP_ENUMERATOR(F14) = GLFW_KEY_F14,
		VKFW_HPP_ENUMERATOR(F15) = GLFW_KEY_F15,
		VKFW_HPP_ENUMERATOR(F16) = GLFW_KEY_F16,
		VKFW_HPP_ENUMERATOR(F17) = GLFW_KEY_F17,
		VKFW_HPP_ENUMERATOR(F18) = GLFW_KEY_F18,
		VKFW_HPP_ENUMERATOR(F19) = GLFW_KEY_F19,
		VKFW_HPP_ENUMERATOR(F20) = GLFW_KEY_F20,
		VKFW_HPP_ENUMERATOR(F21) = GLFW_KEY_F21,
		VKFW_HPP_ENUMERATOR(F22) = GLFW_KEY_F22,
		VKFW_HPP_ENUMERATOR(F23) = GLFW_KEY_F23,
		VKFW_HPP_ENUMERATOR(F24) = GLFW_KEY_F24,
		VKFW_HPP_ENUMERATOR(F25) = GLFW_KEY_F25,
		VKFW_HPP_ENUMERATOR(KeyPad_0) = GLFW_KEY_KP_0,
		VKFW_HPP_ENUMERATOR(KeyPad_1) = GLFW_KEY_KP_1,
		VKFW_HPP_ENUMERATOR(KeyPad_2) = GLFW_KEY_KP_2,
		VKFW_HPP_ENUMERATOR(KeyPad_3) = GLFW_KEY_KP_3,
		VKFW_HPP_ENUMERATOR(KeyPad_4) = GLFW_KEY_KP_4,
		VKFW_HPP_ENUMERATOR(KeyPad_5) = GLFW_KEY_KP_5,
		VKFW_HPP_ENUMERATOR(KeyPad_6) = GLFW_KEY_KP_6,
		VKFW_HPP_ENUMERATOR(KeyPad_7) = GLFW_KEY_KP_7,
		VKFW_HPP_ENUMERATOR(KeyPad_8) = GLFW_KEY_KP_8,
		VKFW_HPP_ENUMERATOR(KeyPad_9) = GLFW_KEY_KP_9,
		VKFW_HPP_ENUMERATOR(KeyPad_Decimal) = GLFW_KEY_KP_DECIMAL,
		VKFW_HPP_ENUMERATOR(KeyPad_Divide) = GLFW_KEY_KP_DIVIDE,
		VKFW_HPP_ENUMERATOR(KeyPad_Multiply) = GLFW_KEY_KP_MULTIPLY,
		VKFW_HPP_ENUMERATOR(KeyPad_Subtract) = GLFW_KEY_KP_SUBTRACT,
		VKFW_HPP_ENUMERATOR(KeyPad_Add) = GLFW_KEY_KP_ADD,
		VKFW_HPP_ENUMERATOR(KeyPad_Enter) = GLFW_KEY_KP_ENTER,
		VKFW_HPP_ENUMERATOR(KeyPad_Equal) = GLFW_KEY_KP_EQUAL,
		VKFW_HPP_ENUMERATOR(LeftShift) = GLFW_KEY_LEFT_SHIFT,
		VKFW_HPP_ENUMERATOR(LeftControl) = GLFW_KEY_LEFT_CONTROL,
		VKFW_HPP_ENUMERATOR(LeftAlt) = GLFW_KEY_LEFT_ALT,
		VKFW_HPP_ENUMERATOR(LeftSuper) = GLFW_KEY_LEFT_SUPER,
		VKFW_HPP_ENUMERATOR(RightShift) = GLFW_KEY_RIGHT_SHIFT,
		VKFW_HPP_ENUMERATOR(RightControl) = GLFW_KEY_RIGHT_CONTROL,
		VKFW_HPP_ENUMERATOR(RightAlt) = GLFW_KEY_RIGHT_ALT,
		VKFW_HPP_ENUMERATOR(RightSuper) = GLFW_KEY_RIGHT_SUPER,
		VKFW_HPP_ENUMERATOR(Menu) = GLFW_KEY_MENU,

		VKFW_HPP_ENUMERATOR(LAST) = GLFW_KEY_LAST
	};

	VKFW_HPP_INLINE VKFW_HPP_STRING_T to_string(Boolean value) {
		switch (value) {
			case Boolean::VKFW_HPP_ENUMERATOR(True): return VKFW_HPP_CHAR_LITERAL"True";
			case Boolean::VKFW_HPP_ENUMERATOR(False): return VKFW_HPP_CHAR_LITERAL"False";
			default: return VKFW_HPP_CHAR_LITERAL"invalid";
		}
	}
	VKFW_HPP_INLINE VKFW_HPP_STRING_T to_string(KeyAction value) {
		switch (value) {
			case KeyAction::VKFW_HPP_ENUMERATOR(Release): return VKFW_HPP_CHAR_LITERAL"Release";
			case KeyAction::VKFW_HPP_ENUMERATOR(Press): return VKFW_HPP_CHAR_LITERAL"Press";
			case KeyAction::VKFW_HPP_ENUMERATOR(Repeat): return VKFW_HPP_CHAR_LITERAL"Repeat";
			default: return VKFW_HPP_CHAR_LITERAL"invalid";
		}
	}
	VKFW_HPP_INLINE VKFW_HPP_STRING_T to_string(MouseButtonAction value) {
		switch (value) {
			case MouseButtonAction::VKFW_HPP_ENUMERATOR(Release): return VKFW_HPP_CHAR_LITERAL"Release";
			case MouseButtonAction::VKFW_HPP_ENUMERATOR(Press): return VKFW_HPP_CHAR_LITERAL"Press";
			default: return VKFW_HPP_CHAR_LITERAL"invalid";
		}
	}
	VKFW_HPP_INLINE VKFW_HPP_STRING_T to_string(JoystickHatState value) {
		switch (value) {
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Centered): return VKFW_HPP_CHAR_LITERAL"Centered";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Up): return VKFW_HPP_CHAR_LITERAL"Up";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Right): return VKFW_HPP_CHAR_LITERAL"Right";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Down): return VKFW_HPP_CHAR_LITERAL"Down";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Left): return VKFW_HPP_CHAR_LITERAL"Left";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Right_Up): return VKFW_HPP_CHAR_LITERAL"Right Up";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Right_Down): return VKFW_HPP_CHAR_LITERAL"Right Down";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Left_Up): return VKFW_HPP_CHAR_LITERAL"Left Up";
			case JoystickHatState::VKFW_HPP_ENUMERATOR(Left_Down): return VKFW_HPP_CHAR_LITERAL"Left Down";
			default: return VKFW_HPP_CHAR_LITERAL"invalid";
		}
	}
	VKFW_HPP_INLINE VKFW_HPP_STRING_T to_string(Key value) {
		switch (value) {
			case Key::VKFW_HPP_ENUMERATOR(Unknown): return VKFW_HPP_CHAR_LITERAL"Unknown";

				/* Printable Keys */
			case Key::VKFW_HPP_ENUMERATOR(Space): return VKFW_HPP_CHAR_LITERAL"Space";
			case Key::VKFW_HPP_ENUMERATOR(Apostrophe): return VKFW_HPP_CHAR_LITERAL"Apostrophe";
			case Key::VKFW_HPP_ENUMERATOR(Comma): return VKFW_HPP_CHAR_LITERAL"Comma";
			case Key::VKFW_HPP_ENUMERATOR(Minus): return VKFW_HPP_CHAR_LITERAL"Minus";
			case Key::VKFW_HPP_ENUMERATOR(Period): return VKFW_HPP_CHAR_LITERAL"Period";
			case Key::VKFW_HPP_ENUMERATOR(Slash): return VKFW_HPP_CHAR_LITERAL"Slash";
			case Key::VKFW_HPP_ENUMERATOR2(0, _0): return VKFW_HPP_CHAR_LITERAL"0";
			case Key::VKFW_HPP_ENUMERATOR2(1, _1): return VKFW_HPP_CHAR_LITERAL"1";
			case Key::VKFW_HPP_ENUMERATOR2(2, _2): return VKFW_HPP_CHAR_LITERAL"2";
			case Key::VKFW_HPP_ENUMERATOR2(3, _3): return VKFW_HPP_CHAR_LITERAL"3";
			case Key::VKFW_HPP_ENUMERATOR2(4, _4): return VKFW_HPP_CHAR_LITERAL"4";
			case Key::VKFW_HPP_ENUMERATOR2(5, _5): return VKFW_HPP_CHAR_LITERAL"5";
			case Key::VKFW_HPP_ENUMERATOR2(6, _6): return VKFW_HPP_CHAR_LITERAL"6";
			case Key::VKFW_HPP_ENUMERATOR2(7, _7): return VKFW_HPP_CHAR_LITERAL"7";
			case Key::VKFW_HPP_ENUMERATOR2(8, _8): return VKFW_HPP_CHAR_LITERAL"8";
			case Key::VKFW_HPP_ENUMERATOR2(9, _9): return VKFW_HPP_CHAR_LITERAL"9";
			case Key::VKFW_HPP_ENUMERATOR(Semicolon): return VKFW_HPP_CHAR_LITERAL"Semicolon";
			case Key::VKFW_HPP_ENUMERATOR(Equal): return VKFW_HPP_CHAR_LITERAL"Equal";
			case Key::VKFW_HPP_ENUMERATOR(A): return VKFW_HPP_CHAR_LITERAL"A";
			case Key::VKFW_HPP_ENUMERATOR(B): return VKFW_HPP_CHAR_LITERAL"B";
			case Key::VKFW_HPP_ENUMERATOR(C): return VKFW_HPP_CHAR_LITERAL"C";
			case Key::VKFW_HPP_ENUMERATOR(D): return VKFW_HPP_CHAR_LITERAL"D";
			case Key::VKFW_HPP_ENUMERATOR(E): return VKFW_HPP_CHAR_LITERAL"E";
			case Key::VKFW_HPP_ENUMERATOR(F): return VKFW_HPP_CHAR_LITERAL"F";
			case Key::VKFW_HPP_ENUMERATOR(G): return VKFW_HPP_CHAR_LITERAL"G";
			case Key::VKFW_HPP_ENUMERATOR(H): return VKFW_HPP_CHAR_LITERAL"H";
			case Key::VKFW_HPP_ENUMERATOR(I): return VKFW_HPP_CHAR_LITERAL"I";
			case Key::VKFW_HPP_ENUMERATOR(J): return VKFW_HPP_CHAR_LITERAL"J";
			case Key::VKFW_HPP_ENUMERATOR(K): return VKFW_HPP_CHAR_LITERAL"K";
			case Key::VKFW_HPP_ENUMERATOR(L): return VKFW_HPP_CHAR_LITERAL"L";
			case Key::VKFW_HPP_ENUMERATOR(M): return VKFW_HPP_CHAR_LITERAL"M";
			case Key::VKFW_HPP_ENUMERATOR(N): return VKFW_HPP_CHAR_LITERAL"N";
			case Key::VKFW_HPP_ENUMERATOR(O): return VKFW_HPP_CHAR_LITERAL"O";
			case Key::VKFW_HPP_ENUMERATOR(P): return VKFW_HPP_CHAR_LITERAL"P";
			case Key::VKFW_HPP_ENUMERATOR(Q): return VKFW_HPP_CHAR_LITERAL"Q";
			case Key::VKFW_HPP_ENUMERATOR(R): return VKFW_HPP_CHAR_LITERAL"R";
			case Key::VKFW_HPP_ENUMERATOR(S): return VKFW_HPP_CHAR_LITERAL"S";
			case Key::VKFW_HPP_ENUMERATOR(T): return VKFW_HPP_CHAR_LITERAL"T";
			case Key::VKFW_HPP_ENUMERATOR(U): return VKFW_HPP_CHAR_LITERAL"U";
			case Key::VKFW_HPP_ENUMERATOR(V): return VKFW_HPP_CHAR_LITERAL"V";
			case Key::VKFW_HPP_ENUMERATOR(W): return VKFW_HPP_CHAR_LITERAL"W";
			case Key::VKFW_HPP_ENUMERATOR(X): return VKFW_HPP_CHAR_LITERAL"X";
			case Key::VKFW_HPP_ENUMERATOR(Y): return VKFW_HPP_CHAR_LITERAL"Y";
			case Key::VKFW_HPP_ENUMERATOR(Z): return VKFW_HPP_CHAR_LITERAL"Z";
			case Key::VKFW_HPP_ENUMERATOR(LeftBracket): return VKFW_HPP_CHAR_LITERAL"LeftBracket";
			case Key::VKFW_HPP_ENUMERATOR(Backslash): return VKFW_HPP_CHAR_LITERAL"Backslash";
			case Key::VKFW_HPP_ENUMERATOR(RightBracket): return VKFW_HPP_CHAR_LITERAL"RightBracket";
			case Key::VKFW_HPP_ENUMERATOR(GraveAccent): return VKFW_HPP_CHAR_LITERAL"GraveAccent";
			case Key::VKFW_HPP_ENUMERATOR(World1): return VKFW_HPP_CHAR_LITERAL"World1";
			case Key::VKFW_HPP_ENUMERATOR(World2): return VKFW_HPP_CHAR_LITERAL"World2";

				/* Function Keys */
			case Key::VKFW_HPP_ENUMERATOR(Escape): return VKFW_HPP_CHAR_LITERAL"Escape";
			case Key::VKFW_HPP_ENUMERATOR(Enter): return VKFW_HPP_CHAR_LITERAL"Enter";
			case Key::VKFW_HPP_ENUMERATOR(Tab): return VKFW_HPP_CHAR_LITERAL"Tab";
			case Key::VKFW_HPP_ENUMERATOR(Backspace): return VKFW_HPP_CHAR_LITERAL"Backspace";
			case Key::VKFW_HPP_ENUMERATOR(Insert): return VKFW_HPP_CHAR_LITERAL"Insert";
			case Key::VKFW_HPP_ENUMERATOR(Delete): return VKFW_HPP_CHAR_LITERAL"Delete";
			case Key::VKFW_HPP_ENUMERATOR(Right): return VKFW_HPP_CHAR_LITERAL"Right";
			case Key::VKFW_HPP_ENUMERATOR(Left): return VKFW_HPP_CHAR_LITERAL"Left";
			case Key::VKFW_HPP_ENUMERATOR(Down): return VKFW_HPP_CHAR_LITERAL"Down";
			case Key::VKFW_HPP_ENUMERATOR(Up): return VKFW_HPP_CHAR_LITERAL"Up";
			case Key::VKFW_HPP_ENUMERATOR(PageUp): return VKFW_HPP_CHAR_LITERAL"PageUp";
			case Key::VKFW_HPP_ENUMERATOR(PageDown): return VKFW_HPP_CHAR_LITERAL"PageDown";
			case Key::VKFW_HPP_ENUMERATOR(Home): return VKFW_HPP_CHAR_LITERAL"Home";
			case Key::VKFW_HPP_ENUMERATOR(End): return VKFW_HPP_CHAR_LITERAL"End";
			case Key::VKFW_HPP_ENUMERATOR(CapsLock): return VKFW_HPP_CHAR_LITERAL"CapsLock";
			case Key::VKFW_HPP_ENUMERATOR(ScrollLock): return VKFW_HPP_CHAR_LITERAL"ScrollLock";
			case Key::VKFW_HPP_ENUMERATOR(NumLock): return VKFW_HPP_CHAR_LITERAL"NumLock";
			case Key::VKFW_HPP_ENUMERATOR(PrintScreen): return VKFW_HPP_CHAR_LITERAL"PrintScreen";
			case Key::VKFW_HPP_ENUMERATOR(Pause): return VKFW_HPP_CHAR_LITERAL"Pause";
			case Key::VKFW_HPP_ENUMERATOR(F1): return VKFW_HPP_CHAR_LITERAL"F1";
			case Key::VKFW_HPP_ENUMERATOR(F2): return VKFW_HPP_CHAR_LITERAL"F2";
			case Key::VKFW_HPP_ENUMERATOR(F3): return VKFW_HPP_CHAR_LITERAL"F3";
			case Key::VKFW_HPP_ENUMERATOR(F4): return VKFW_HPP_CHAR_LITERAL"F4";
			case Key::VKFW_HPP_ENUMERATOR(F5): return VKFW_HPP_CHAR_LITERAL"F5";
			case Key::VKFW_HPP_ENUMERATOR(F6): return VKFW_HPP_CHAR_LITERAL"F6";
			case Key::VKFW_HPP_ENUMERATOR(F7): return VKFW_HPP_CHAR_LITERAL"F7";
			case Key::VKFW_HPP_ENUMERATOR(F8): return VKFW_HPP_CHAR_LITERAL"F8";
			case Key::VKFW_HPP_ENUMERATOR(F9): return VKFW_HPP_CHAR_LITERAL"F9";
			case Key::VKFW_HPP_ENUMERATOR(F10): return VKFW_HPP_CHAR_LITERAL"F10";
			case Key::VKFW_HPP_ENUMERATOR(F11): return VKFW_HPP_CHAR_LITERAL"F11";
			case Key::VKFW_HPP_ENUMERATOR(F12): return VKFW_HPP_CHAR_LITERAL"F12";
			case Key::VKFW_HPP_ENUMERATOR(F13): return VKFW_HPP_CHAR_LITERAL"F13";
			case Key::VKFW_HPP_ENUMERATOR(F14): return VKFW_HPP_CHAR_LITERAL"F14";
			case Key::VKFW_HPP_ENUMERATOR(F15): return VKFW_HPP_CHAR_LITERAL"F15";
			case Key::VKFW_HPP_ENUMERATOR(F16): return VKFW_HPP_CHAR_LITERAL"F16";
			case Key::VKFW_HPP_ENUMERATOR(F17): return VKFW_HPP_CHAR_LITERAL"F17";
			case Key::VKFW_HPP_ENUMERATOR(F18): return VKFW_HPP_CHAR_LITERAL"F18";
			case Key::VKFW_HPP_ENUMERATOR(F19): return VKFW_HPP_CHAR_LITERAL"F19";
			case Key::VKFW_HPP_ENUMERATOR(F20): return VKFW_HPP_CHAR_LITERAL"F20";
			case Key::VKFW_HPP_ENUMERATOR(F21): return VKFW_HPP_CHAR_LITERAL"F21";
			case Key::VKFW_HPP_ENUMERATOR(F22): return VKFW_HPP_CHAR_LITERAL"F22";
			case Key::VKFW_HPP_ENUMERATOR(F23): return VKFW_HPP_CHAR_LITERAL"F23";
			case Key::VKFW_HPP_ENUMERATOR(F24): return VKFW_HPP_CHAR_LITERAL"F24";
			case Key::VKFW_HPP_ENUMERATOR(F25): return VKFW_HPP_CHAR_LITERAL"F25";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_0): return VKFW_HPP_CHAR_LITERAL"KeyPad 0";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_1): return VKFW_HPP_CHAR_LITERAL"KeyPad 1";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_2): return VKFW_HPP_CHAR_LITERAL"KeyPad 2";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_3): return VKFW_HPP_CHAR_LITERAL"KeyPad 3";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_4): return VKFW_HPP_CHAR_LITERAL"KeyPad 4";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_5): return VKFW_HPP_CHAR_LITERAL"KeyPad 5";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_6): return VKFW_HPP_CHAR_LITERAL"KeyPad 6";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_7): return VKFW_HPP_CHAR_LITERAL"KeyPad 7";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_8): return VKFW_HPP_CHAR_LITERAL"KeyPad 8";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_9): return VKFW_HPP_CHAR_LITERAL"KeyPad 9";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Decimal): return VKFW_HPP_CHAR_LITERAL"KeyPad Decimal";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Divide): return VKFW_HPP_CHAR_LITERAL"KeyPad Divide";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Multiply): return VKFW_HPP_CHAR_LITERAL"KeyPad Multiply";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Subtract): return VKFW_HPP_CHAR_LITERAL"KeyPad Subtract";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Add): return VKFW_HPP_CHAR_LITERAL"KeyPad Add";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Enter): return VKFW_HPP_CHAR_LITERAL"KeyPad Enter";
			case Key::VKFW_HPP_ENUMERATOR(KeyPad_Equal): return VKFW_HPP_CHAR_LITERAL"KeyPad Equal";
			case Key::VKFW_HPP_ENUMERATOR(LeftShift): return VKFW_HPP_CHAR_LITERAL"LeftShift";
			case Key::VKFW_HPP_ENUMERATOR(LeftControl): return VKFW_HPP_CHAR_LITERAL"LeftControl";
			case Key::VKFW_HPP_ENUMERATOR(LeftAlt): return VKFW_HPP_CHAR_LITERAL"LeftAlt";
			case Key::VKFW_HPP_ENUMERATOR(LeftSuper): return VKFW_HPP_CHAR_LITERAL"LeftSuper";
			case Key::VKFW_HPP_ENUMERATOR(RightShift): return VKFW_HPP_CHAR_LITERAL"RightShift";
			case Key::VKFW_HPP_ENUMERATOR(RightControl): return VKFW_HPP_CHAR_LITERAL"RightControl";
			case Key::VKFW_HPP_ENUMERATOR(RightAlt): return VKFW_HPP_CHAR_LITERAL"RightAlt";
			case Key::VKFW_HPP_ENUMERATOR(RightSuper): return VKFW_HPP_CHAR_LITERAL"RightSuper";
			case Key::VKFW_HPP_ENUMERATOR(Menu): return VKFW_HPP_CHAR_LITERAL"Menu";
			default: return VKFW_HPP_CHAR_LITERAL"invalid";
		}
	}

	template <typename RefType>
	using Optional = VULKAN_HPP_NAMESPACE::Optional<RefType>;

#if !defined(VKFW_HPP_NO_SMART_HANDLE)
	template <typename Type> using UniqueHandleTraits
		= VULKAN_HPP_NAMESPACE::UniqueHandleTraits<Type, VULKAN_HPP_DEFAULT_DISPATCHER_TYPE>;

	template <typename Type> using UniqueHandle
		= VULKAN_HPP_NAMESPACE::UniqueHandle<Type, VULKAN_HPP_DEFAULT_DISPATCHER_TYPE>;
#endif

	template <typename Type>
	struct isHandleType {
		static VKFW_HPP_CONST_OR_CONSTEXPR bool value = false;
	};
}